name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub Login
        run: docker login -u ${{ secret.DOCKER_HUB_USER}} -p ${{ secret.DOCKER_HUB_PASSWORD }}
